<?php

return [
    'categories' => [
        'webserver' => ['label' => 'Web Server', 'order' => 1],
        'runtime' => ['label' => 'Runtime', 'order' => 2],
        'database' => ['label' => 'Database', 'order' => 3],
        'cache' => ['label' => 'Cache', 'order' => 4],
        'mail' => ['label' => 'Mail', 'order' => 5],
        'dns' => ['label' => 'DNS', 'order' => 6],
        'security' => ['label' => 'Security', 'order' => 7],
        'panel' => ['label' => 'Panel Services', 'order' => 8],
    ],

    'apps' => [
        // Single-version apps
        'nginx' => [
            'name' => 'Nginx',
            'category' => 'webserver',
            'type' => 'single',
            'service_name' => 'nginx',
            'packages' => ['nginx'],
            'config_files' => [
                'main' => '/etc/nginx/nginx.conf',
            ],
            'is_system' => false,
            'is_critical' => true,
        ],
        'mysql' => [
            'name' => 'MySQL',
            'category' => 'database',
            'type' => 'single',
            'service_name' => 'mysql',
            'packages' => ['mysql-server'],
            'config_files' => [
                'main' => '/etc/mysql/mysql.conf.d/mysqld.cnf',
            ],
            'is_system' => false,
            'is_critical' => true,
        ],
        'redis' => [
            'name' => 'Redis',
            'category' => 'cache',
            'type' => 'single',
            'service_name' => 'redis-server',
            'packages' => ['redis-server'],
            'config_files' => [
                'main' => '/etc/redis/redis.conf',
            ],
            'is_system' => false,
            'is_critical' => true,
        ],
        'postfix' => [
            'name' => 'Postfix',
            'category' => 'mail',
            'type' => 'single',
            'service_name' => 'postfix',
            'packages' => ['postfix'],
            'config_files' => [
                'main' => '/etc/postfix/main.cf',
                'master' => '/etc/postfix/master.cf',
            ],
            'is_system' => false,
        ],
        'dovecot' => [
            'name' => 'Dovecot',
            'category' => 'mail',
            'type' => 'single',
            'service_name' => 'dovecot',
            'packages' => ['dovecot-imapd', 'dovecot-pop3d'],
            'config_files' => [
                'main' => '/etc/dovecot/dovecot.conf',
            ],
            'is_system' => false,
        ],
        'named' => [
            'name' => 'BIND DNS',
            'category' => 'dns',
            'type' => 'single',
            'service_name' => 'named',
            'packages' => ['bind9'],
            'config_files' => [
                'main' => '/etc/bind/named.conf',
                'options' => '/etc/bind/named.conf.options',
            ],
            'is_system' => false,
        ],
        'fail2ban' => [
            'name' => 'Fail2Ban',
            'category' => 'security',
            'type' => 'single',
            'service_name' => 'fail2ban',
            'packages' => ['fail2ban'],
            'config_files' => [
                'jail' => '/etc/fail2ban/jail.local',
            ],
            'is_system' => false,
        ],
        'ufw' => [
            'name' => 'UFW Firewall',
            'category' => 'security',
            'type' => 'single',
            'service_name' => 'ufw',
            'packages' => ['ufw'],
            'config_files' => [],
            'is_system' => false,
        ],
        'composer' => [
            'name' => 'Composer',
            'category' => 'runtime',
            'type' => 'single',
            'service_name' => null,
            'packages' => [],
            'config_files' => [],
            'detect_command' => 'which composer',
            'is_system' => false,
        ],
        'vsispanel-horizon' => [
            'name' => 'VSISPanel Horizon',
            'category' => 'panel',
            'type' => 'single',
            'service_name' => 'vsispanel-horizon',
            'packages' => [],
            'config_files' => [],
            'is_system' => true,
        ],
        'vsispanel-reverb' => [
            'name' => 'VSISPanel WebSocket',
            'category' => 'panel',
            'type' => 'single',
            'service_name' => 'vsispanel-reverb',
            'packages' => [],
            'config_files' => [],
            'is_system' => true,
        ],
        'vsispanel-terminal' => [
            'name' => 'VSISPanel Terminal',
            'category' => 'panel',
            'type' => 'single',
            'service_name' => 'vsispanel-terminal',
            'packages' => [],
            'config_files' => [],
            'is_system' => true,
        ],

        // Multi-version apps
        'php' => [
            'name' => 'PHP',
            'category' => 'runtime',
            'type' => 'multi_version',
            'available_versions' => ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4'],
            'service_pattern' => 'php{version}-fpm',
            'package_pattern' => 'php{version}-fpm',
            'extra_packages' => [
                'php{version}-cli', 'php{version}-common', 'php{version}-mysql',
                'php{version}-xml', 'php{version}-curl', 'php{version}-mbstring',
                'php{version}-zip', 'php{version}-gd', 'php{version}-bcmath',
                'php{version}-intl', 'php{version}-readline',
            ],
            'config_pattern' => [
                'php_ini' => '/etc/php/{version}/fpm/php.ini',
                'fpm' => '/etc/php/{version}/fpm/php-fpm.conf',
                'pool' => '/etc/php/{version}/fpm/pool.d/www.conf',
            ],
            'ppa' => 'ppa:ondrej/php',
            'is_system' => false,
        ],
        'nodejs' => [
            'name' => 'Node.js',
            'category' => 'runtime',
            'type' => 'multi_version',
            'available_versions' => ['18', '20', '22'],
            'install_method' => 'binary',
            'install_dir' => '/usr/local/lib/nodejs',
            'packages' => [],
            'config_files' => [],
            'is_system' => false,
        ],
        'python' => [
            'name' => 'Python',
            'category' => 'runtime',
            'type' => 'multi_version',
            'available_versions' => ['3.10', '3.11', '3.12'],
            'package_pattern' => 'python{version}',
            'extra_packages' => ['python{version}-venv', 'python{version}-dev'],
            'ppa' => 'ppa:deadsnakes/ppa',
            'config_files' => [],
            'is_system' => false,
        ],
    ],
];
