# HTTP to HTTPS redirect for {{ $server_name }}
# Generated by VSISPanel at {{ now()->toISOString() }}

server {
    listen 80;
    listen [::]:80;
    server_name {{ $server_name }} {{ $www_server_name }};

    # Let's Encrypt ACME challenge (must be accessible over HTTP)
    location ^~ /.well-known/acme-challenge/ {
        allow all;
        default_type "text/plain";
        root {{ $domain->document_root_path }};
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
