# Virtual Host configuration for {{ $server_name }} (HTTPS)
# Generated by VSISPanel at {{ now()->toISOString() }}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {{ $server_name }} {{ $www_server_name }};

    root {{ $document_root }};
    index index.php index.html index.htm;

    # SSL Certificate
    ssl_certificate {{ $cert_path }};
    ssl_certificate_key {{ $key_path }};
@if(!empty($chain_path))
    ssl_trusted_certificate {{ $chain_path }};
@endif

    # SSL Settings
    ssl_protocols {{ $ssl_protocols }};
    ssl_ciphers {{ $ssl_ciphers }};
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

@if($ocsp_stapling)
    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
@endif

    # Logging
    access_log {{ $access_log }};
    error_log {{ $error_log }};

    # Security headers
@foreach($security_headers as $header => $value)
    add_header {{ $header }} "{{ $value }}" always;
@endforeach
@if($hsts_enabled)
    add_header Strict-Transport-Security "max-age={{ $hsts_max_age }}; includeSubDomains; preload" always;
@endif

    # Disable server tokens
    server_tokens off;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    # Client settings
    client_max_body_size 100M;
    client_body_timeout 60s;
    client_header_timeout 60s;

    # Main location block
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP processing
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:{{ $php_socket }};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        include fastcgi_params;

        # Timeouts
        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 60s;
        fastcgi_read_timeout 60s;

        # Buffering
        fastcgi_buffering on;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 16 16k;
    }

    # Deny access to hidden files (except .well-known)
    location ~ /\.(?!well-known) {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Deny access to sensitive files
    location ~* (?:\.(?:bak|conf|dist|fla|in[ci]|log|psd|sh|sql|sw[op])|~)$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Static files caching
    location ~* \.(jpg|jpeg|gif|png|ico|css|js|pdf|txt|tar|gz|woff|woff2|ttf|svg|eot)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    # Favicon and robots
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    # Let's Encrypt ACME challenge
    location ^~ /.well-known/acme-challenge/ {
        allow all;
        default_type "text/plain";
        root {{ $document_root }};
    }
}
