; PHP-FPM Pool Configuration for Domain: {{ $domain->name }}
; Generated by VSISPanel at {{ now()->toISOString() }}
; PHP Version: {{ $php_version }}
; Pool Name: {{ $pool_name }}

[{{ $pool_name }}]

; User and group (runs as domain owner)
user = {{ $username }}
group = {{ $username }}

; Socket settings
listen = {{ $socket_path }}
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process manager settings
pm = {{ $settings['pm'] ?? 'dynamic' }}
pm.max_children = {{ $settings['max_children'] ?? 5 }}
@if(($settings['pm'] ?? 'dynamic') === 'dynamic')
pm.start_servers = {{ $settings['start_servers'] ?? 2 }}
pm.min_spare_servers = {{ $settings['min_spare_servers'] ?? 1 }}
pm.max_spare_servers = {{ $settings['max_spare_servers'] ?? 3 }}
@endif
pm.max_requests = {{ $settings['max_requests'] ?? 500 }}
pm.process_idle_timeout = {{ $settings['process_idle_timeout'] ?? '10s' }}

; Status page (for monitoring)
pm.status_path = /fpm-status-{{ $pool_name }}

; Ping page for health checks
ping.path = /fpm-ping-{{ $pool_name }}
ping.response = pong

; Logging
access.log = /home/{{ $username }}/domains/{{ $domain->name }}/logs/php-fpm-access.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"
slowlog = /home/{{ $username }}/domains/{{ $domain->name }}/logs/php-fpm-slow.log
request_slowlog_timeout = 5s

; Error handling
catch_workers_output = yes
decorate_workers_output = no

; Security restrictions
@if(!empty($disabled_functions))
php_admin_value[disable_functions] = {{ $disabled_functions }}
@endif
php_admin_value[open_basedir] = /home/{{ $username }}/domains/{{ $domain->name }}:/tmp:/var/lib/php:/usr/share/php
php_admin_value[session.save_path] = /home/{{ $username }}/domains/{{ $domain->name }}/tmp
php_admin_value[upload_tmp_dir] = /home/{{ $username }}/domains/{{ $domain->name }}/tmp
php_admin_value[sys_temp_dir] = /home/{{ $username }}/domains/{{ $domain->name }}/tmp
php_admin_flag[expose_php] = off

; Resource limits (Domain-specific PHP settings)
php_admin_value[memory_limit] = {{ $php_settings['memory_limit'] ?? '256M' }}
php_admin_value[max_execution_time] = {{ $php_settings['max_execution_time'] ?? 30 }}
php_admin_value[max_input_time] = {{ $php_settings['max_input_time'] ?? 60 }}
php_admin_value[post_max_size] = {{ $php_settings['post_max_size'] ?? '64M' }}
php_admin_value[upload_max_filesize] = {{ $php_settings['upload_max_filesize'] ?? '64M' }}
php_admin_value[max_input_vars] = {{ $php_settings['max_input_vars'] ?? 1000 }}

; Error logging
php_admin_value[error_log] = /home/{{ $username }}/domains/{{ $domain->name }}/logs/php-error.log
php_admin_flag[log_errors] = on
php_admin_value[error_reporting] = E_ALL & ~E_DEPRECATED & ~E_STRICT
php_admin_flag[display_errors] = {{ isset($php_settings['display_errors']) && ($php_settings['display_errors'] === 'on' || $php_settings['display_errors'] === true || $php_settings['display_errors'] === '1') ? 'on' : 'off' }}
php_admin_flag[display_startup_errors] = off

; Security flags
php_admin_flag[allow_url_fopen] = on
php_admin_flag[allow_url_include] = off
php_admin_flag[cgi.fix_pathinfo] = off

; Session settings
php_admin_value[session.gc_maxlifetime] = {{ $php_settings['session.gc_maxlifetime'] ?? 1440 }}
php_admin_value[session.cookie_httponly] = 1
php_admin_value[session.cookie_secure] = 1
php_admin_value[session.use_strict_mode] = 1

; Timezone
php_admin_value[date.timezone] = {{ $php_settings['date.timezone'] ?? $user->timezone ?? 'Asia/Ho_Chi_Minh' }}

; OPcache settings (if enabled globally)
php_admin_value[opcache.validate_timestamps] = 1
php_admin_value[opcache.revalidate_freq] = 2

; Realpath cache
php_admin_value[realpath_cache_size] = 4096K
php_admin_value[realpath_cache_ttl] = 600

; Environment variables
env[HOSTNAME] = $HOSTNAME
env[TMP] = /home/{{ $username }}/domains/{{ $domain->name }}/tmp
env[TMPDIR] = /home/{{ $username }}/domains/{{ $domain->name }}/tmp
env[TEMP] = /home/{{ $username }}/domains/{{ $domain->name }}/tmp
env[USER] = {{ $username }}
env[DOMAIN] = {{ $domain->name }}
