<?php

/**
 * VSISPanel SSO Plugin for Roundcube
 *
 * Enables Single Sign-On from VSISPanel to Roundcube webmail.
 * This plugin handles automatic login using tokens generated by VSISPanel.
 *
 * @author VSISPanel
 * @license MIT
 */
class vsispanel_sso extends rcube_plugin
{
    /**
     * Plugin initialization.
     */
    public function init()
    {
        $this->add_hook('startup', [$this, 'startup']);
        $this->add_hook('authenticate', [$this, 'authenticate']);
    }

    /**
     * Handle startup - check for SSO token.
     */
    public function startup($args)
    {
        $rcmail = rcmail::get_instance();

        // Skip if already logged in
        if ($rcmail->user && $rcmail->user->ID) {
            return $args;
        }

        // Check for SSO token in request
        $token = rcube_utils::get_input_value('_autologin', rcube_utils::INPUT_GET);

        if (!$token) {
            return $args;
        }

        // Validate token via VSISPanel API
        $credentials = $this->validate_token($token);

        if ($credentials) {
            // Store credentials for authentication hook
            $rcmail->output->set_env('vsispanel_sso_user', $credentials['email']);
            $rcmail->output->set_env('vsispanel_sso_pass', $credentials['password']);

            // Trigger login
            $_POST['_user'] = $credentials['email'];
            $_POST['_pass'] = $credentials['password'];
            $_POST['_action'] = 'login';
            $args['task'] = 'login';
            $args['action'] = 'login';
        }

        return $args;
    }

    /**
     * Handle authentication hook.
     */
    public function authenticate($args)
    {
        $rcmail = rcmail::get_instance();

        // Check if we have SSO credentials
        $sso_user = $rcmail->output->get_env('vsispanel_sso_user');
        $sso_pass = $rcmail->output->get_env('vsispanel_sso_pass');

        if ($sso_user && $sso_pass) {
            $args['user'] = $sso_user;
            $args['pass'] = $sso_pass;
            $args['cookiecheck'] = false;
            $args['valid'] = true;
        }

        return $args;
    }

    /**
     * Validate SSO token with VSISPanel API.
     */
    private function validate_token($token)
    {
        $rcmail = rcmail::get_instance();

        // Get API configuration
        $api_url = $rcmail->config->get('vsispanel_api_url', 'http://localhost:8000/api');
        $api_key = $rcmail->config->get('vsispanel_api_key', '');

        if (empty($api_key)) {
            rcube::write_log('vsispanel_sso', 'API key not configured');
            return false;
        }

        // Call VSISPanel API to validate token
        $url = rtrim($api_url, '/') . '/mail/webmail/validate-sso';

        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => json_encode(['token' => $token]),
            CURLOPT_HTTPHEADER => [
                'Content-Type: application/json',
                'Accept: application/json',
                'X-API-Key: ' . $api_key,
            ],
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 10,
            CURLOPT_SSL_VERIFYPEER => false, // Set to true in production with valid SSL
        ]);

        $response = curl_exec($ch);
        $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error = curl_error($ch);
        curl_close($ch);

        if ($error) {
            rcube::write_log('vsispanel_sso', 'API request failed: ' . $error);
            return false;
        }

        if ($http_code !== 200) {
            rcube::write_log('vsispanel_sso', 'API returned HTTP ' . $http_code);
            return false;
        }

        $data = json_decode($response, true);

        if (!$data || !isset($data['success']) || !$data['success']) {
            rcube::write_log('vsispanel_sso', 'API validation failed');
            return false;
        }

        if (!isset($data['data']['email']) || !isset($data['data']['password'])) {
            rcube::write_log('vsispanel_sso', 'Invalid API response format');
            return false;
        }

        return [
            'email' => $data['data']['email'],
            'password' => $data['data']['password'],
        ];
    }
}
