# Dovecot authentication configuration - Generated by VSISPanel
# {{ now()->format('Y-m-d H:i:s') }}

# Disable anonymous authentication
disable_plaintext_auth = yes

# Authentication mechanisms
auth_mechanisms = plain login

# Password database configuration
passdb {
  driver = passwd-file
  args = scheme=SSHA512 {{ $passwdFile }}
}

# User database configuration
userdb {
  driver = passwd-file
  args = {{ $passwdFile }}
  default_fields = uid={{ $vmailUid }} gid={{ $vmailGid }} home={{ $mailBaseDir }}/%d/%n
}

# Master users (for webmail/admin access)
# passdb {
#   driver = passwd-file
#   args = {{ dirname($passwdFile) }}/master-users
#   master = yes
# }

# Authentication service for Postfix SASL
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }

  unix_listener auth-userdb {
    mode = 0600
    user = vmail
  }

  user = dovecot
}

# Authentication worker service
service auth-worker {
  user = vmail
}
