# Dovecot LMTP configuration - Generated by VSISPanel
# {{ now()->format('Y-m-d H:i:s') }}

# LMTP service configuration for receiving mail from Postfix
protocol lmtp {
  mail_plugins = $mail_plugins sieve quota
  postmaster_address = postmaster@{{ $hostname }}
}

# LMTP socket for Postfix
service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

# Sieve plugin for filtering
plugin {
  sieve = ~/.dovecot.sieve
  sieve_dir = ~/sieve
  sieve_global_path = /etc/dovecot/sieve/default.sieve
  sieve_before = /etc/dovecot/sieve/before.d/
  sieve_after = /etc/dovecot/sieve/after.d/
}
