# Dovecot mail configuration - Generated by VSISPanel
# {{ now()->format('Y-m-d H:i:s') }}

# Mail location
mail_location = maildir:{{ $mailBaseDir }}/%d/%n/Maildir

# Mail UID/GID
mail_uid = {{ $vmailUid }}
mail_gid = {{ $vmailGid }}

# First valid UID/GID
first_valid_uid = {{ $vmailUid }}
first_valid_gid = {{ $vmailGid }}

# Mail home
mail_home = {{ $mailBaseDir }}/%d/%n

# Mailbox permissions
mail_privileged_group = mail

# Namespace configuration
namespace inbox {
  inbox = yes
  separator = /

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Archive {
    auto = no
    special_use = \Archive
  }
}

# Mail process settings
mbox_write_locks = fcntl

# Quota settings
mail_plugins = $mail_plugins quota

protocol imap {
  mail_plugins = $mail_plugins imap_quota
}

plugin {
  quota = maildir:User quota
  quota_rule = *:storage=1G
  quota_warning = storage=95%% quota-warning 95 %u
  quota_warning2 = storage=80%% quota-warning 80 %u
}
