# Dovecot configuration - Generated by VSISPanel
# {{ now()->format('Y-m-d H:i:s') }}

# Protocols to enable
protocols = {{ implode(' ', $protocols) }}

# Listen addresses
listen = *, ::

# Base directory where to store runtime data
base_dir = /var/run/dovecot/

# Instance name (for identification)
instance_name = dovecot

# Login processes
login_greeting = VSISPanel Mail Server

# SSL/TLS settings
ssl = required
ssl_cert = <{{ $sslCert }}
ssl_key = <{{ $sslKey }}
ssl_min_protocol = TLSv1.2
ssl_cipher_list = HIGH:!aNULL:!MD5:!3DES
ssl_prefer_server_ciphers = yes

# Authentication
auth_mechanisms = plain login

# Logging
log_path = syslog
syslog_facility = mail
auth_verbose = no
mail_debug = no

# Include config directory
!include conf.d/*.conf
!include_try local.conf
