<?php

declare(strict_types=1);

namespace App\Modules\Mail\Services;

use App\Services\CommandResult;
use App\Services\SystemCommandExecutor;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use RuntimeException;

class RspamdService
{
    protected string $apiUrl;
    protected string $apiPassword;
    protected string $configPath;
    protected string $localConfigPath;

    public function __construct(
        protected SystemCommandExecutor $executor
    ) {
        $this->apiUrl = config('vsispanel.mail.rspamd_api_url', 'http://127.0.0.1:11334');
        $this->apiPassword = config('vsispanel.mail.rspamd_api_password', '');
        $this->configPath = config('vsispanel.mail.rspamd_config_path', '/etc/rspamd');
        $this->localConfigPath = "{$this->configPath}/local.d";
    }

    /**
     * Get Rspamd service status.
     */
    public function getStatus(): array
    {
        $statusResult = $this->executor->executeAsRoot('systemctl', ['is-active', 'rspamd']);
        $isRunning = $statusResult->success && trim($statusResult->stdout) === 'active';

        $version = 'Unknown';
        $versionResult = $this->executor->execute('rspamd', ['--version']);
        if ($versionResult->success) {
            preg_match('/Rspamd\s+([\d.]+)/', $versionResult->stdout, $matches);
            $version = $matches[1] ?? 'Unknown';
        }

        return [
            'running' => $isRunning,
            'version' => $version,
            'api_url' => $this->apiUrl,
        ];
    }

    /**
     * Get Rspamd statistics.
     */
    public function getStatistics(): array
    {
        try {
            $response = $this->apiRequest('GET', '/stat');

            if (!$response) {
                return $this->getDefaultStatistics();
            }

            return [
                'scanned' => $response['scanned'] ?? 0,
                'learned' => $response['learned'] ?? 0,
                'spam_count' => $response['spam_count'] ?? 0,
                'ham_count' => $response['ham_count'] ?? 0,
                'connections' => $response['connections'] ?? 0,
                'control_connections' => $response['control_connections'] ?? 0,
                'pools_allocated' => $response['pools_allocated'] ?? 0,
                'pools_freed' => $response['pools_freed'] ?? 0,
                'bytes_allocated' => $response['bytes_allocated'] ?? 0,
                'uptime' => $response['uptime'] ?? 0,
            ];
        } catch (\Exception $e) {
            return $this->getDefaultStatistics();
        }
    }

    /**
     * Get default empty statistics.
     */
    protected function getDefaultStatistics(): array
    {
        return [
            'scanned' => 0,
            'learned' => 0,
            'spam_count' => 0,
            'ham_count' => 0,
            'connections' => 0,
            'control_connections' => 0,
            'pools_allocated' => 0,
            'pools_freed' => 0,
            'bytes_allocated' => 0,
            'uptime' => 0,
        ];
    }

    /**
     * Get spam score threshold for a domain (or global).
     */
    public function getSpamScore(?string $domain = null): array
    {
        $actionsFile = "{$this->localConfigPath}/actions.conf";

        $defaults = [
            'reject' => 15.0,
            'add_header' => 6.0,
            'greylist' => 4.0,
            'rewrite_subject' => null,
        ];

        if (!File::exists($actionsFile)) {
            return $defaults;
        }

        $content = File::get($actionsFile);

        // Parse the config file
        preg_match('/reject\s*=\s*([\d.]+)/', $content, $rejectMatch);
        preg_match('/add_header\s*=\s*([\d.]+)/', $content, $headerMatch);
        preg_match('/greylist\s*=\s*([\d.]+)/', $content, $greylistMatch);
        preg_match('/rewrite_subject\s*=\s*([\d.]+)/', $content, $rewriteMatch);

        return [
            'reject' => isset($rejectMatch[1]) ? (float) $rejectMatch[1] : $defaults['reject'],
            'add_header' => isset($headerMatch[1]) ? (float) $headerMatch[1] : $defaults['add_header'],
            'greylist' => isset($greylistMatch[1]) ? (float) $greylistMatch[1] : $defaults['greylist'],
            'rewrite_subject' => isset($rewriteMatch[1]) ? (float) $rewriteMatch[1] : null,
        ];
    }

    /**
     * Set spam score thresholds.
     */
    public function setSpamScore(array $scores): void
    {
        $this->ensureLocalConfigDir();

        $actionsFile = "{$this->localConfigPath}/actions.conf";

        $config = "# Rspamd actions configuration\n";
        $config .= "# Generated by VSISPanel\n\n";

        if (isset($scores['reject'])) {
            $config .= "reject = {$scores['reject']};\n";
        }
        if (isset($scores['add_header'])) {
            $config .= "add_header = {$scores['add_header']};\n";
        }
        if (isset($scores['greylist'])) {
            $config .= "greylist = {$scores['greylist']};\n";
        }
        if (isset($scores['rewrite_subject']) && $scores['rewrite_subject'] !== null) {
            $config .= "rewrite_subject = {$scores['rewrite_subject']};\n";
        }

        File::put($actionsFile, $config);
        $this->executor->executeAsRoot('chown', ['_rspamd:_rspamd', $actionsFile]);
        $this->executor->executeAsRoot('chmod', ['644', $actionsFile]);

        $this->reload();
    }

    /**
     * Get whitelist entries.
     */
    public function getWhitelist(): array
    {
        return $this->getList('whitelist');
    }

    /**
     * Add email/domain to whitelist.
     */
    public function addToWhitelist(string $entry, string $type = 'from'): void
    {
        $this->addToList('whitelist', $entry, $type);
    }

    /**
     * Remove from whitelist.
     */
    public function removeFromWhitelist(string $entry): void
    {
        $this->removeFromList('whitelist', $entry);
    }

    /**
     * Get blacklist entries.
     */
    public function getBlacklist(): array
    {
        return $this->getList('blacklist');
    }

    /**
     * Add email/domain to blacklist.
     */
    public function addToBlacklist(string $entry, string $type = 'from'): void
    {
        $this->addToList('blacklist', $entry, $type);
    }

    /**
     * Remove from blacklist.
     */
    public function removeFromBlacklist(string $entry): void
    {
        $this->removeFromList('blacklist', $entry);
    }

    /**
     * Get list entries (whitelist or blacklist).
     */
    protected function getList(string $listName): array
    {
        $listFile = "{$this->localConfigPath}/{$listName}.inc";

        if (!File::exists($listFile)) {
            return [];
        }

        $content = File::get($listFile);
        $entries = [];

        // Parse entries: "entry" or entry@domain.com
        preg_match_all('/"([^"]+)"/', $content, $matches);

        foreach ($matches[1] as $entry) {
            // Determine type based on format
            $type = str_contains($entry, '@') ? 'email' : 'domain';
            $entries[] = [
                'entry' => $entry,
                'type' => $type,
            ];
        }

        return $entries;
    }

    /**
     * Add entry to a list.
     */
    protected function addToList(string $listName, string $entry, string $type): void
    {
        $this->ensureLocalConfigDir();

        $listFile = "{$this->localConfigPath}/{$listName}.inc";

        // Get existing entries
        $entries = $this->getList($listName);

        // Check if already exists
        foreach ($entries as $existing) {
            if ($existing['entry'] === $entry) {
                return; // Already exists
            }
        }

        // Add new entry
        $entries[] = [
            'entry' => $entry,
            'type' => $type,
        ];

        // Write back
        $this->writeList($listFile, $entries);

        // Update multimap configuration
        $this->updateMultimapConfig($listName);

        $this->reload();
    }

    /**
     * Remove entry from a list.
     */
    protected function removeFromList(string $listName, string $entry): void
    {
        $listFile = "{$this->localConfigPath}/{$listName}.inc";

        if (!File::exists($listFile)) {
            return;
        }

        $entries = $this->getList($listName);
        $entries = array_filter($entries, fn($e) => $e['entry'] !== $entry);

        $this->writeList($listFile, array_values($entries));
        $this->reload();
    }

    /**
     * Write list to file.
     */
    protected function writeList(string $file, array $entries): void
    {
        $content = "# Generated by VSISPanel\n";

        foreach ($entries as $entry) {
            $content .= "\"{$entry['entry']}\"\n";
        }

        File::put($file, $content);
        $this->executor->executeAsRoot('chown', ['_rspamd:_rspamd', $file]);
        $this->executor->executeAsRoot('chmod', ['644', $file]);
    }

    /**
     * Update multimap configuration for whitelist/blacklist.
     */
    protected function updateMultimapConfig(string $listName): void
    {
        $multimapFile = "{$this->localConfigPath}/multimap.conf";

        $symbol = $listName === 'whitelist' ? 'WHITELIST_SENDER' : 'BLACKLIST_SENDER';
        $prefilter = $listName === 'whitelist' ? 'true' : 'false';
        $action = $listName === 'whitelist' ? 'accept' : 'reject';

        $config = <<<CONF
# {$listName} configuration - Generated by VSISPanel
{$symbol} {
    type = "from";
    filter = "email:domain";
    map = "\$LOCAL_CONFDIR/local.d/{$listName}.inc";
    prefilter = {$prefilter};
    action = "{$action}";
    description = "Sender {$listName}";
}

CONF;

        // Read existing config and update or append
        $existingConfig = File::exists($multimapFile) ? File::get($multimapFile) : '';

        // Remove existing block for this list
        $pattern = '/# ' . preg_quote($listName, '/') . ' configuration.*?' . preg_quote($symbol, '/') . '\s*\{[^}]+\}\s*/s';
        $existingConfig = preg_replace($pattern, '', $existingConfig);

        // Append new config
        $existingConfig .= "\n" . $config;

        File::put($multimapFile, trim($existingConfig) . "\n");
        $this->executor->executeAsRoot('chown', ['_rspamd:_rspamd', $multimapFile]);
        $this->executor->executeAsRoot('chmod', ['644', $multimapFile]);
    }

    /**
     * Train message as ham (not spam).
     */
    public function trainHam(string $messageContent): bool
    {
        try {
            $response = $this->apiRequest('POST', '/learnham', $messageContent);
            return $response !== null && ($response['success'] ?? false);
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Train message as spam.
     */
    public function trainSpam(string $messageContent): bool
    {
        try {
            $response = $this->apiRequest('POST', '/learnspam', $messageContent);
            return $response !== null && ($response['success'] ?? false);
        } catch (\Exception $e) {
            return false;
        }
    }

    /**
     * Scan a message and get spam score.
     */
    public function scanMessage(string $messageContent): array
    {
        try {
            $response = $this->apiRequest('POST', '/checkv2', $messageContent, [
                'Content-Type' => 'message/rfc822',
            ]);

            if (!$response) {
                return ['error' => 'Failed to scan message'];
            }

            return [
                'score' => $response['score'] ?? 0,
                'required_score' => $response['required_score'] ?? 0,
                'action' => $response['action'] ?? 'no action',
                'is_spam' => ($response['score'] ?? 0) >= ($response['required_score'] ?? 999),
                'symbols' => $response['symbols'] ?? [],
            ];
        } catch (\Exception $e) {
            return ['error' => $e->getMessage()];
        }
    }

    /**
     * Get Rspamd history (recent scans).
     */
    public function getHistory(int $limit = 100): array
    {
        try {
            $response = $this->apiRequest('GET', "/history?limit={$limit}");
            return $response['rows'] ?? [];
        } catch (\Exception $e) {
            return [];
        }
    }

    /**
     * Reload Rspamd configuration.
     */
    public function reload(): CommandResult
    {
        return $this->executor->executeAsRoot('systemctl', ['reload', 'rspamd']);
    }

    /**
     * Restart Rspamd service.
     */
    public function restart(): CommandResult
    {
        return $this->executor->executeAsRoot('systemctl', ['restart', 'rspamd']);
    }

    /**
     * Make API request to Rspamd.
     */
    protected function apiRequest(string $method, string $endpoint, ?string $body = null, array $headers = []): ?array
    {
        $url = rtrim($this->apiUrl, '/') . $endpoint;

        $defaultHeaders = [
            'Accept' => 'application/json',
        ];

        if ($this->apiPassword) {
            $defaultHeaders['Password'] = $this->apiPassword;
        }

        $headers = array_merge($defaultHeaders, $headers);

        try {
            $request = Http::withHeaders($headers)->timeout(10);

            if ($method === 'POST' && $body) {
                $response = $request->withBody($body, $headers['Content-Type'] ?? 'text/plain')->post($url);
            } else {
                $response = $request->get($url);
            }

            if ($response->successful()) {
                return $response->json();
            }

            return null;
        } catch (\Exception $e) {
            return null;
        }
    }

    /**
     * Ensure local config directory exists.
     */
    protected function ensureLocalConfigDir(): void
    {
        if (!File::isDirectory($this->localConfigPath)) {
            $this->executor->executeAsRoot('mkdir', ['-p', $this->localConfigPath]);
            $this->executor->executeAsRoot('chown', ['_rspamd:_rspamd', $this->localConfigPath]);
        }
    }

    /**
     * Generate default Rspamd configuration.
     */
    public function generateDefaultConfig(): void
    {
        $this->ensureLocalConfigDir();

        // Actions config
        $this->setSpamScore([
            'reject' => 15,
            'add_header' => 6,
            'greylist' => 4,
        ]);

        // Worker config for performance
        $workerConfig = <<<CONF
# Worker configuration - Generated by VSISPanel
count = 2;
CONF;

        File::put("{$this->localConfigPath}/worker-normal.inc", $workerConfig);

        // Logging config
        $loggingConfig = <<<CONF
# Logging configuration - Generated by VSISPanel
level = "info";
log_urls = true;
debug_modules = [];
CONF;

        File::put("{$this->localConfigPath}/logging.inc", $loggingConfig);

        $this->reload();
    }
}
